#!/usr/bin/env python3
"""
generate_summary.py — Write a Markdown job summary for a GitHub Actions run.

Usage:
    python3 generate_summary.py >> "$GITHUB_STEP_SUMMARY"

Reads:
    audit-work/bundle/audit-bundle.json   (generated by generate_audit_bundle.py)
    audit-work/prepare/gpg-verify.log
    audit-work/prepare/build-environment.txt

Reads pipeline context from GitHub Actions env vars:
    BASE_SHA, GIT_SHA  (from job outputs)
    GITHUB_RUN_ID, GITHUB_RUN_NUMBER, GITHUB_ACTOR, GITHUB_REF,
    GITHUB_SHA, GITHUB_REPOSITORY, GITHUB_EVENT_NAME, GITHUB_SERVER_URL
"""
import json
import os
import datetime
import sys


def read_text(path: str) -> str:
    try:
        with open(path) as f:
            return f.read().strip()
    except OSError:
        return "(not available)"


def env(key: str, default: str = "") -> str:
    return os.environ.get(key, default)


def main() -> None:
    base_sha   = env("BASE_SHA")
    git_sha    = env("GIT_SHA")
    run_id     = env("GITHUB_RUN_ID")
    run_number = env("GITHUB_RUN_NUMBER")
    actor      = env("GITHUB_ACTOR")
    ref        = env("GITHUB_REF")
    full_sha   = env("GITHUB_SHA")
    repo       = env("GITHUB_REPOSITORY")
    event_name = env("GITHUB_EVENT_NAME")
    server_url = env("GITHUB_SERVER_URL")
    now        = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    run_url    = f"{server_url}/{repo}/actions/runs/{run_id}"

    bundle: dict = {}
    try:
        with open("audit-work/bundle/audit-bundle.json") as f:
            bundle = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        pass

    skus_data: dict = bundle.get("skus", {})

    lines = [
        f"# HCS Image Build — Run #{run_number}",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Run | [{run_id}]({run_url}) |",
        f"| Triggered by | `{actor}` via `{event_name}` |",
        f"| Ref | `{ref}` |",
        f"| Git commit | `{full_sha}` (short: `{git_sha}`) |",
        f"| Base image SHA-256 | `{base_sha}` |",
        f"| GPG key | `D2EB44626FDDC30B513D5BB71A5D6C4C7DB87C81` |",
        f"| Audit generated | `{now}` |",
        "",
        "## SKU Build Results",
        "",
        "| SKU | Result | Artifact SHA-256 | Packages |",
        "|---|---|---|---|",
    ]

    overall_ok = True
    for sku in ["base", "cis-l1", "cis-l2"]:
        data   = skus_data.get(sku, {})
        result = data.get("build_result", "not-run")
        icon   = "✅" if result == "success" else "❌"
        sha    = data.get("artifact_sha256") or "—"
        sha_s  = f"`{sha[:32]}…`" if len(sha) > 32 else f"`{sha}`"
        pkgs   = data.get("sbom_package_count")
        pkgs_s = str(pkgs) if pkgs is not None else "—"
        lines.append(f"| `{sku}` | {icon} {result} | {sha_s} | {pkgs_s} |")
        if result != "success":
            overall_ok = False

    status_msg = (
        "✅ All SKUs built and validated."
        if overall_ok
        else "⚠️ One or more SKUs failed — review the logs above."
    )

    lines += [
        "",
        status_msg,
        "",
        "## Artefacts",
        "",
        "| Name | Retention | Contents |",
        "|---|---|---|",
        "| `prepare-audit` | 90 days | GPG verification log, base image SHA-256, build environment |",
        "| `image-{sku}` | 30 days | Final qcow2 image (copy to OBS/S3 for long-term storage) |",
        "| `metadata-{sku}` | 90 days | Provenance manifest, SBOM (tsv), SHA-256 checksums, qemu-img info |",
        "| `logs-{sku}` | 90 days | QEMU serial console log, Packer debug log |",
        "| `audit-bundle` | 90 days | Aggregated JSON provenance bundle + all metadata |",
        "",
        "## Base Image GPG Verification",
        "",
        "```",
        read_text("audit-work/prepare/gpg-verify.log"),
        "```",
        "",
        "## Build Environment",
        "",
        "```",
        read_text("audit-work/prepare/build-environment.txt"),
        "```",
    ]

    print("\n".join(lines))


if __name__ == "__main__":
    main()
